"use client";

import { useCompletion } from "ai/react"; // imports from Vercel
import ChatHeader from "@/components/chat-header";
import { Companion, Message } from "@prisma/client";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import ChatForm from "@/components/chat-form";
import ChatMessages from "@/components/chat-messages";
import { ChatMessageProps } from "@/components/chat-message";

// The ChatClient component receives the companion as a prop. The companion object contains the messages field, which is an array of Message objects. The _count field contains the number of messages in the array.
interface ChatClientProps {
  companion: Companion & {
    messages: Message[];
    _count: {
      messages: number;
    };
  };
}

const ChatClient = ({ companion }: ChatClientProps) => {
  const router = useRouter();
  const [messages, setMessages] = useState<ChatMessageProps[]>(companion.messages);

  // Use the AI tool to generate a response to the user's message.
  const { input, isLoading, handleInputChange, handleSubmit, setInput } =
    useCompletion({
      api: `/api/chat/${companion.id}`,
      onFinish(prompt, completion) {
        const systemMessage: ChatMessageProps = {
          role: "system",
          content: completion,
        };

        setMessages((current) => [...current, systemMessage]);
        setInput("");
        router.refresh();
      },
    });

  // onSubmit:
  const onSubmit = (e: FormEvent<HTMLFormElement>) => {
    const userMessage: ChatMessageProps = {
      role: "user",
      content: input,
    };
    setMessages((current) => [...current, userMessage]);

    handleSubmit(e);
  };

  return (
    <div className="flex flex-col h-full p-4  space-y-2 sm:w-[550px]  md:w-[700px] lg:w-[950px] xl:w-[1100px]">
      <ChatHeader companion={companion} />
      <ChatMessages
        companion={companion}
        messages={messages}
        isLoading={isLoading}
      />
      <ChatForm
        input={input}
        isLoading={isLoading}
        handleInputChange={handleInputChange}
        onSubmit={onSubmit}
      />
    </div>
  );
};

export default ChatClient;

// This is a TypeScript React code snippet that defines a component that uses the useCompletion hook. The useCompletion hook is a custom hook that handles user input and sends it to a chat API endpoint. When the API returns a response, the onFinish callback function is called with the prompt and completion arguments. The completion argument is the response from the API, which is then displayed as a system message in the chat window.

// The onSubmit function is called when the user submits a message. It creates a new message object with the user's input and adds it to the messages state array. It then calls the handleSubmit function, which is provided by the useCompletion hook, to send the user's input to the chat API.


// **** API endpoint ****
// The API endpoint /api/chat/${companion.id} is used to send a message from the user to the server and receive a response from the server.

// The ${companion.id} part of the endpoint is a dynamic parameter that is replaced with the ID of the companion object that is passed as a prop to the ChatClient component. This allows the server to identify which companion the user is chatting with and provide appropriate responses.

// The useCompletion hook is used to make a request to this endpoint and receive a response. When the user submits a message, the onFinish callback function is called with the prompt and completion generated by the AI tool. The completion is used to create a system message, which is added to the messages state using the setMessages function.